version: "3"
services:
  travel-db:
    image: "postgres"
    container_name: "travel"
    environment:
      - POSTGRES_USER=mila
      - POSTGRES_PASSWORD=wp123
      - POSTGRES_DB=travel
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
#version: '3.9'
#
#services:
#  postgres:
#    image: postgres:14-alpine
#    restart: always
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: postgres
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: sara
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#
#volumes:
#  postgres-data:
#    driver: local